namespace WeaponSkins.Shared;

// item_games.txt
public enum AttributeDefinitionIndex : ushort
{
    SET_ITEM_TEXTURE_PREFAB = 6, // int convert to float
    SET_ITEM_TEXTURE_SEED = 7,
    SET_ITEM_TEXTURE_WEAR = 8,


    KILL_EATER = 80, // int as float
    KILL_EATER_SCORE_TYPE = 81, // int as float


    CUSTOM_NAME_ATTR = 111, // CAttribute_String


    STICKER_SLOT_0_ID = 113, // int as float
    STICKER_SLOT_0_WEAR = 114,
    STICKER_SLOT_0_SCALE = 115,
    STICKER_SLOT_0_ROTATION = 116,
    STICKER_SLOT_1_ID = 117, // int as float
    STICKER_SLOT_1_WEAR = 118,
    STICKER_SLOT_1_SCALE = 119,
    STICKER_SLOT_1_ROTATION = 120,
    STICKER_SLOT_2_ID = 121, // int as float
    STICKER_SLOT_2_WEAR = 122,
    STICKER_SLOT_2_SCALE = 123,
    STICKER_SLOT_2_ROTATION = 124,
    STICKER_SLOT_3_ID = 125, // int as float
    STICKER_SLOT_3_WEAR = 126,
    STICKER_SLOT_3_SCALE = 127,
    STICKER_SLOT_3_ROTATION = 128,
    STICKER_SLOT_4_ID = 129, // int as float
    STICKER_SLOT_4_WEAR = 130,
    STICKER_SLOT_4_SCALE = 131,
    STICKER_SLOT_4_ROTATION = 132,
    STICKER_SLOT_5_ID = 133, // int as float
    STICKER_SLOT_5_WEAR = 134,
    STICKER_SLOT_5_SCALE = 135,
    STICKER_SLOT_5_ROTATION = 136,


    STICKER_SLOT_0_OFFSET_X = 278,
    STICKER_SLOT_0_OFFSET_Y = 279,
    STICKER_SLOT_1_OFFSET_X = 280,
    STICKER_SLOT_1_OFFSET_Y = 281,
    STICKER_SLOT_2_OFFSET_X = 282,
    STICKER_SLOT_2_OFFSET_Y = 283,
    STICKER_SLOT_3_OFFSET_X = 284,
    STICKER_SLOT_3_OFFSET_Y = 285,
    STICKER_SLOT_4_OFFSET_X = 286,
    STICKER_SLOT_4_OFFSET_Y = 287,
    STICKER_SLOT_5_OFFSET_X = 288,
    STICKER_SLOT_5_OFFSET_Y = 289,
    STICKER_SLOT_0_SCHEMA = 290, // int as float
    STICKER_SLOT_1_SCHEMA = 291, // int as float
    STICKER_SLOT_2_SCHEMA = 292, // int as float
    STICKER_SLOT_3_SCHEMA = 293, // int as float
    STICKER_SLOT_4_SCHEMA = 294, // int as float
    STICKER_SLOT_5_SCHEMA = 295, // int as float


    KEYCHAIN_SLOT_0_ID = 299, // int as float
    KEYCHAIN_SLOT_0_OFFSET_X = 300,
    KEYCHAIN_SLOT_0_OFFSET_Y = 301,
    KEYCHAIN_SLOT_0_OFFSET_Z = 302,
    KEYCHAIN_SLOT_0_SEED = 306, // int as float
}